coverage:
	cd Bubble/ && make run && gcov prog.c
	cd Insertion/ && make run && gcov prog.c
	cd Merge/ && make run && gcov prog.c
	cd Quick/ && make run && gcov prog.c
	cd Selection/ && make run && gcov prog.c